services:
  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  worker:
    build: .
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: ["perl", "script/koha_plugin_store", "minion", "worker"]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: koha_plugin_store
      POSTGRES_PASSWORD: koha_plugin_store
      POSTGRES_DB: koha_plugin_store
    ports:
      - "127.0.0.1:55432:5432"
    volumes:
      - koha_plugin_store_pgdata:/var/lib/postgresql/data

volumes:
  koha_plugin_store_pgdata:
